services:
  backend:
    build:
      context: ./infernosource-monorepo/apps/backend
      dockerfile: Dockerfile
    container_name: infernosource-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./infernosource-monorepo:/app
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
