FROM python:3.10

WORKDIR /app

COPY ./ /app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Start Celery worker
CMD ["celery", "-A", "apps.backend.celery_worker.celery", "worker", "--loglevel=info"]
